# Generated by Django 5.1.6 on 2025-02-19 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Besucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('standort', models.CharField(choices=[('München', 'München'), ('Berlin', 'Berlin'), ('Hamburg', 'Hamburg'), ('Stuttgart', 'Stuttgart')], max_length=50)),
                ('besuchstag', models.DateField(default=datetime.date.today)),
                ('besuchsgrund', models.TextField()),
                ('weitere_informationen', models.TextField()),
            ],
        ),
    ]
